[project]
name = "mortgage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "great-tables>=0.20.0",
    "marimo>=0.18.4",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
]
